import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import ContactPage from "./contact";
import ProjectsPage from "./projects";
import SkillsPage from "./skills";
import WorkPage from "./work";
import NavMenu from "../components/navMenu";
import Header from "../components/common/header";
import {useState} from "react";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const [isMenu, setIsMenu] = useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com"/>
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
          <link href="https://fonts.googleapis.com/css2?family=Rowdies:wght@300;400;700&display=swap"
                        rel="stylesheet"/>
          <link href="/dist/output.css" rel="stylesheet"/>
      </Head>
      <main className={styles.main}>
        <NavMenu isOpen={isMenu} setIsOpen={()=> setIsMenu(!isMenu)}/>
        <Header onClick={()=> setIsMenu(!isMenu)}/>
        {/*<ContactPage/>*/}
        <ProjectsPage/>
        <SkillsPage/>
        <WorkPage/>
      </main>
    </>
  )
}
